### ISSUE TITLE
About 'sample_loop' method

### ISSUE THREAD

**Issue by ken-take-it-so-so** [DavidRuhe/simple-variational-diffusion-models#4]
Hello.  
This line bothers me.  
https://github.com/DavidRuhe/simple-variational-diffusion-models/blob/a4ecc61a5c200341b4b0b7586fcfe65697750d9e/src/main.py#L404  
I think you want to achieve this.
![スクリーンショット 2022-10-19 145843](https://user-images.githubusercontent.com/109563059/196608962-3fa923b9-846f-41be-8057-6dad50d7d7d6.png)  
However, please see below.
```python
import torch

timesteps = torch.linspace(0, 1, 5)
print(timesteps)
print(len(timesteps))
```
Output  
```
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
5
```
When using `torch.linspace`, the width is $1 / (T-1)$.  
I think below is better.
```python
timesteps = torch.arange(0, 1, (1/self.num_timesteps))
timesteps = torch.cat((timesteps, torch.tensor([1])))

for i in tqdm(
    reversed(range(1, self.num_timesteps+1)),
    desc="sampling loop time step",
    total=self.num_timesteps,
):
```
I'm a beginner of deep learning programing. If I misunderstand, could you indicate me ?

**Comment by DavidRuhe** [comment]
Thanks for your suggestion. I think it is correct. However, I believe the performance will not be highly degraded by this error. If you like, please leave a pull request!
